apiVersion: v1
description: File, Block, and Object Storage Services for your Cloud-Native Environment
icon: https://rook.io/images/logos/rook/rook-logo-color-on-transparent.png
name: rook-ceph
sources:
- https://github.com/rook/rook
version: v1.0.0
