appVersion: 7.1.1
description: Kibana
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/kibana.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: kibana
sources:
- https://github.com/elastic/kibana
version: 7.1.1
