---
# Source: webhook-alidns/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-alidns
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-alidns:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-alidns
    namespace: default
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-alidns:auth-delegator
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-alidns
    namespace: default
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-alidns:domain-solver
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
rules:
  - apiGroups:
      - acme.lin07.me
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-alidns:domain-solver
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-alidns:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager

---
# Source: webhook-alidns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-alidns
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: webhook-alidns
    release: cert-manager-webhook-alidns

---
# Source: webhook-alidns/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cert-manager-webhook-alidns
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
spec:
  replicas: 
  selector:
    matchLabels:
      app: webhook-alidns
      release: cert-manager-webhook-alidns
  template:
    metadata:
      labels:
        app: webhook-alidns
        release: cert-manager-webhook-alidns
    spec:
      serviceAccountName: cert-manager-webhook-alidns
      containers:
        - name: webhook-alidns
          image: "lin07/cert-manager-webhook-alidns:latest"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "acme.lin07.me"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
            
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-alidns-webhook-tls

---
# Source: webhook-alidns/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.acme.lin07.me
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
  annotations:
    certmanager.k8s.io/inject-ca-from: "default/cert-manager-webhook-alidns-webhook-tls"
spec:
  group: acme.lin07.me
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-alidns
    namespace: default
  version: v1alpha1

---
# Source: webhook-alidns/templates/pki.yaml
---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: cert-manager-webhook-alidns-selfsign
  namespace: "default"
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
spec:
  selfSigned: {}

---

# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-manager-webhook-alidns-ca
  namespace: "default"
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
spec:
  secretName: cert-manager-webhook-alidns-ca
  duration: 43800h # 5y
  issuerRef:
    name: cert-manager-webhook-alidns-selfsign
  commonName: "ca.webhook-alidns.cert-manager"
  isCA: true

---

# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: cert-manager-webhook-alidns-ca
  namespace: "default"
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
spec:
  ca:
    secretName: cert-manager-webhook-alidns-ca

---

# Finally, generate a serving certificate for the webhook to use
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-manager-webhook-alidns-webhook-tls
  namespace: "default"
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: cert-manager-webhook-alidns
    heritage: Tiller
spec:
  secretName: cert-manager-webhook-alidns-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: cert-manager-webhook-alidns-ca
  dnsNames:
  - cert-manager-webhook-alidns
  - cert-manager-webhook-alidns.default
  - cert-manager-webhook-alidns.default.svc

